name: docker-image-sync
on:
  push:
    branches: [ main ]

jobs:
  image-sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: 镜像同步配置处理
      run: |
        sed -i 's/DOCKERHUB_PASSWORD/${{ secrets.DOCKER_PASSWORD }}/g' config.json
        
    - name: 下载image-sync工具包
      run: |
        wget https://github.com/AliyunContainerService/image-syncer/releases/download/v1.5.4/image-syncer-v1.5.4-linux-amd64.tar.gz
        tar -zxf image-syncer-v1.5.4-linux-amd64.tar.gz
      
    - name: 执行同步镜像
      run: |
        ./image-syncer --proc=2 --config=config.json --retries=2
